import { ALL_MODULES, DESIGNATIONS, MODULES, PERMISSIONS, ROLES } from "./navigation";

const HOPE_MODULES = ALL_MODULES;
const RIVER_MODULES = [
  MODULES.PROJECTS,
  MODULES.SITES,
  MODULES.WORKERS,
  MODULES.ATTENDANCE,
  MODULES.DOCUMENTS,
  MODULES.REPORTS,
];

export const PERSONAS = [
  {
    id: "platform_admin",
    name: "Ayesha Karim",
    email: "admin@orvix.com",
    role: ROLES.PLATFORM_ADMIN,
    roleLabel: "Main Platform Admin",
    orgName: "ORVIX Platform",
    orgHint: "All NGOs",
    designation: null,
    designationLabel: null,
    enabledModules: [],
    permissions: [],
    initials: "AK",
  },
  {
    id: "ngo_admin_hope",
    name: "Nadia Rahman",
    email: "ngoadmin@hope.org",
    role: ROLES.NGO_ADMIN,
    roleLabel: "NGO Admin",
    orgName: "Hope Foundation",
    orgHint: "All modules enabled",
    designation: null,
    designationLabel: null,
    enabledModules: HOPE_MODULES,
    permissions: [],
    initials: "NR",
  },
  {
    id: "ngo_admin_river",
    name: "Karim Hossain",
    email: "ngoadmin@river.org",
    role: ROLES.NGO_ADMIN,
    roleLabel: "NGO Admin",
    orgName: "River Aid",
    orgHint: "Limited modules",
    designation: null,
    designationLabel: null,
    enabledModules: RIVER_MODULES,
    permissions: [],
    initials: "KH",
  },
  {
    id: "store_officer",
    name: "Rafi Ahmed",
    email: "store@hope.org",
    role: ROLES.WORKER,
    roleLabel: "Worker / Employee",
    orgName: "Hope Foundation",
    orgHint: "Store / Logistics",
    designation: DESIGNATIONS.STORE_LOGISTICS_OFFICER,
    designationLabel: "Store / Logistics Officer",
    enabledModules: HOPE_MODULES,
    permissions: [PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.DISTRIBUTION_VIEW],
    initials: "RA",
  },
  {
    id: "field_worker",
    name: "Laila Akter",
    email: "field@hope.org",
    role: ROLES.WORKER,
    roleLabel: "Worker / Employee",
    orgName: "Hope Foundation",
    orgHint: "Field operations",
    designation: DESIGNATIONS.FIELD_WORKER,
    designationLabel: "Field Worker",
    enabledModules: HOPE_MODULES,
    permissions: [PERMISSIONS.ACTIVITIES_VIEW],
    initials: "LA",
  },
  {
    id: "project_worker",
    name: "Imran Khan",
    email: "project@hope.org",
    role: ROLES.WORKER,
    roleLabel: "Worker / Employee",
    orgName: "Hope Foundation",
    orgHint: "Project operations",
    designation: DESIGNATIONS.PROJECT_WORKER,
    designationLabel: "Project Worker",
    enabledModules: HOPE_MODULES,
    permissions: [PERMISSIONS.ACTIVITIES_VIEW],
    initials: "IK",
  },
  {
    id: "data_entry",
    name: "Sadia Noor",
    email: "data@hope.org",
    role: ROLES.WORKER,
    roleLabel: "Worker / Employee",
    orgName: "Hope Foundation",
    orgHint: "Data entry only",
    designation: DESIGNATIONS.DATA_ENTRY_OFFICER,
    designationLabel: "Data Entry Officer",
    enabledModules: [MODULES.DATA_ENTRY, MODULES.DOCUMENTS],
    permissions: [PERMISSIONS.DATA_ENTRY_VIEW],
    initials: "SN",
  },
];

export const PERSONA_STORAGE_KEY = "orvix.previewPersona";

export function getPersona(id) {
  return PERSONAS.find((persona) => persona.id === id) ?? PERSONAS[1];
}
